//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.30 at 04:11:16 PM EEST 
//


package eu.openminted.registry.domain;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for identificationInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="identificationInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resourceNames">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="resourceName" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;restriction base="&lt;http://www.meta-share.org/OMTD-SHARE_XMLSchema>myString">
 *                         &lt;/restriction>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="descriptions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="description" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;restriction base="&lt;http://www.meta-share.org/OMTD-SHARE_XMLSchema>myString">
 *                         &lt;/restriction>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="resourceShortNames" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="resourceShortName" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;restriction base="&lt;http://www.meta-share.org/OMTD-SHARE_XMLSchema>myString">
 *                         &lt;/restriction>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="identifiers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="identifier" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}resourceIdentifierType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "identificationInfoType", propOrder = {
    "resourceNames",
    "descriptions",
    "resourceShortNames",
    "identifiers"
})
public class IdentificationInfo {

	@XmlElementWrapper(name = "resourceNames")
    @XmlElement(name = "resourceName", required = true)
    protected List<LangAttributeField> resourceNames;
	
	@XmlElementWrapper(name = "descriptions")
    @XmlElement(name = "description", required = true)
    protected List<LangAttributeField> descriptions;
	
	@XmlElementWrapper(name = "resourceShortNames")
    @XmlElement(name = "resourceShortName", required = true)
    protected List<LangAttributeField> resourceShortNames;
	
	@XmlElementWrapper(name = "identifiers")
    @XmlElement(name = "identifier", required = true)
    protected List<ResourceIdentifier> identifiers;

    /**
     * Gets the value of the resourceNames property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceNames }
     *     
     */
    public List<LangAttributeField> getResourceNames() {
        return resourceNames;
    }

    /**
     * Sets the value of the resourceNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceNames }
     *     
     */
    public void setResourceNames(List<LangAttributeField> value) {
        this.resourceNames = value;
    }

    /**
     * Gets the value of the descriptions property.
     * 
     * @return
     *     possible object is
     *     {@link Descriptions }
     *     
     */
    public List<LangAttributeField> getDescriptions() {
        return descriptions;
    }

    /**
     * Sets the value of the descriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Descriptions }
     *     
     */
    public void setDescriptions(List<LangAttributeField> value) {
        this.descriptions = value;
    }

    /**
     * Gets the value of the resourceShortNames property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceShortNames }
     *     
     */
    public List<LangAttributeField> getResourceShortNames() {
        return resourceShortNames;
    }

    /**
     * Sets the value of the resourceShortNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceShortNames }
     *     
     */
    public void setResourceShortNames(List<LangAttributeField> value) {
        this.resourceShortNames = value;
    }

    /**
     * Gets the value of the identifiers property.
     * 
     * @return
     *     possible object is
     *     {@link Identifiers }
     *     
     */
    public List<ResourceIdentifier> getIdentifiers() {
        return identifiers;
    }

    /**
     * Sets the value of the identifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifiers }
     *     
     */
    public void setIdentifiers(List<ResourceIdentifier> value) {
        this.identifiers = value;
    }

}
