//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.29 at 02:58:21 PM EEST 
//


package eu.openminted.registry.domain;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for languageDescriptionTextInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="languageDescriptionTextInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mediaType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}lingualityInfo"/>
 *         &lt;element name="language">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}languageInfo" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="metalanguage" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}metalanguageInfo" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Modality" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}modalityInfo" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="size">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}sizeInfo" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="domain" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}domainInfo" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="timeClassification" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}timeCoverageInfo" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="geographicClassifications" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}geographicCoverageInfo" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}creationInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "languageDescriptionTextInfo", propOrder = {
    "mediaType",
    "lingualityInfo",
    "languages",
    "metalanguages",
    "modalities",
    "sizes",
    "domains",
    "timeClassifications",
    "geographicClassifications",
    "creationInfo"
})
public class LanguageDescriptionTextInfo {

    @XmlElement(required = true)
    protected String mediaType;
    @XmlElement(required = true)
    protected LingualityInfo lingualityInfo;
    
    @XmlElementWrapper(name = "languages")
    @XmlElement(name = "languageInfo",required = true)
    protected List<LanguageInfo> languages;
    
    @XmlElementWrapper(name = "metalanguages")
    @XmlElement(name = "metalanguageInfo")
    protected List<LanguageInfo> metalanguages;
    
    @XmlElementWrapper(name = "modalities")
    @XmlElement(name = "modalityInfo")
    protected List<ModalityInfo> modalities;
    
    
    @XmlElementWrapper(name = "sizes")
    @XmlElement(name = "sizeInfo",required = true)
    protected List<SizeInfo> sizes;
    
    @XmlElementWrapper(name = "domains")
    @XmlElement(name = "domainInfo")
    protected List<DomainInfo> domains;
    
    @XmlElementWrapper(name = "timeClassifications")
    @XmlElement(name = "timeCoverageInfo")
    protected List<TimeCoverageInfo> timeClassifications;
    
    @XmlElementWrapper(name = "geographicClassifications")
    @XmlElement(name = "geographicCoverageInfo")
    protected List<GeographicCoverageInfo> geographicClassifications;
    
    protected CreationInfo creationInfo;

    /**
     * Gets the value of the mediaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaType() {
        return mediaType;
    }

    /**
     * Sets the value of the mediaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaType(String value) {
        this.mediaType = value;
    }

    /**
     * Gets the value of the lingualityInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LingualityInfo }
     *     
     */
    public LingualityInfo getLingualityInfo() {
        return lingualityInfo;
    }

    /**
     * Sets the value of the lingualityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LingualityInfo }
     *     
     */
    public void setLingualityInfo(LingualityInfo value) {
        this.lingualityInfo = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link Language }
     *     
     */
    public List<LanguageInfo> getLanguage() {
        return languages;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link Language }
     *     
     */
    public void setLanguage(List<LanguageInfo> value) {
        this.languages = value;
    }

    /**
     * Gets the value of the metalanguage property.
     * 
     * @return
     *     possible object is
     *     {@link Metalanguage }
     *     
     */
    public List<LanguageInfo> getMetalanguage() {
        return metalanguages;
    }

    /**
     * Sets the value of the metalanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Metalanguage }
     *     
     */
    public void setMetalanguage(List<LanguageInfo> value) {
        this.metalanguages = value;
    }

    /**
     * Gets the value of the Modality property.
     * 
     * @return
     *     possible object is
     *     {@link Modality }
     *     
     */
    public List<ModalityInfo> getModality() {
        return modalities;
    }

    /**
     * Sets the value of the Modality property.
     * 
     * @param value
     *     allowed object is
     *     {@link Modality }
     *     
     */
    public void setModality(List<ModalityInfo> value) {
        this.modalities = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link Size }
     *     
     */
    public List<SizeInfo> getSize() {
        return sizes;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link Size }
     *     
     */
    public void setSize(List<SizeInfo> value) {
        this.sizes = value;
    }

    /**
     * Gets the value of the domain property.
     * 
     * @return
     *     possible object is
     *     {@link Domain }
     *     
     */
    public List<DomainInfo> getDomain() {
        return domains;
    }

    /**
     * Sets the value of the domain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Domain }
     *     
     */
    public void setDomain(List<DomainInfo> value) {
        this.domains = value;
    }

    /**
     * Gets the value of the timeClassification property.
     * 
     * @return
     *     possible object is
     *     {@link TimeClassification }
     *     
     */
    public List<TimeCoverageInfo> getTimeClassification() {
        return timeClassifications;
    }

    /**
     * Sets the value of the timeClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeClassification }
     *     
     */
    public void setTimeClassification(List<TimeCoverageInfo> value) {
        this.timeClassifications = value;
    }

    /**
     * Gets the value of the geographicClassifications property.
     * 
     * @return
     *     possible object is
     *     {@link GeographicClassifications }
     *     
     */
    public List<GeographicCoverageInfo> getGeographicClassifications() {
        return geographicClassifications;
    }

    /**
     * Sets the value of the geographicClassifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographicClassifications }
     *     
     */
    public void setGeographicClassifications(List<GeographicCoverageInfo> value) {
        this.geographicClassifications = value;
    }

    /**
     * Gets the value of the creationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CreationInfo }
     *     
     */
    public CreationInfo getCreationInfo() {
        return creationInfo;
    }

    /**
     * Sets the value of the creationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreationInfo }
     *     
     */
    public void setCreationInfo(CreationInfo value) {
        this.creationInfo = value;
    }

}
