//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.29 at 02:58:21 PM EEST 
//


package eu.openminted.registry.domain;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}metadataHeaderInfo"/>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}languageDescriptionInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlType(name = "", propOrder = {
    "metadataHeaderInfo",
    "languageDescriptionInfo"
})
@XmlRootElement(name = "languageDescriptionMetadataRecord", namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema")
public class LanguageDescription {

    @XmlElement(required = true)
    protected MetadataHeaderInfo metadataHeaderInfo;
    @XmlElement(required = true)
    protected LanguageDescriptionInfo languageDescriptionInfo;

    public LanguageDescription() {
		// TODO Auto-generated constructor stub
	}
    
    
    
    public LanguageDescription(MetadataHeaderInfo metadataHeaderInfo,
			LanguageDescriptionInfo languageDescriptionInfo) {
		super();
		this.metadataHeaderInfo = metadataHeaderInfo;
		this.languageDescriptionInfo = languageDescriptionInfo;
	}



	/**
     * Gets the value of the metadataHeaderInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MetadataHeaderInfo }
     *     
     */
    public MetadataHeaderInfo getMetadataHeaderInfo() {
        return metadataHeaderInfo;
    }

    /**
     * Sets the value of the metadataHeaderInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetadataHeaderInfo }
     *     
     */
    public void setMetadataHeaderInfo(MetadataHeaderInfo value) {
        this.metadataHeaderInfo = value;
    }

    /**
     * Gets the value of the languageDescriptionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageDescriptionInfo }
     *     
     */
    public LanguageDescriptionInfo getLanguageDescriptionInfo() {
        return languageDescriptionInfo;
    }

    /**
     * Sets the value of the languageDescriptionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageDescriptionInfo }
     *     
     */
    public void setLanguageDescriptionInfo(LanguageDescriptionInfo value) {
        this.languageDescriptionInfo = value;
    }

}
