//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.29 at 02:58:21 PM EEST 
//


package eu.openminted.registry.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}languageDescriptionTextInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "languageDescriptionTextInfo"
})
public class LanguageDescriptionMedia {

    @XmlElement(required = true)
    protected LanguageDescriptionTextInfo languageDescriptionTextInfo;

    /**
     * Gets the value of the languageDescriptionTextInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageDescriptionTextInfo }
     *     
     */
    public LanguageDescriptionTextInfo getLanguageDescriptionTextInfo() {
        return languageDescriptionTextInfo;
    }

    /**
     * Sets the value of the languageDescriptionTextInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageDescriptionTextInfo }
     *     
     */
    public void setLanguageDescriptionTextInfo(LanguageDescriptionTextInfo value) {
        this.languageDescriptionTextInfo = value;
    }

}
