//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.29 at 02:58:21 PM EEST 
//


package eu.openminted.registry.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for languageDescriptionOperationInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="languageDescriptionOperationInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}runningEnvironmentInfo" minOccurs="0"/>
 *         &lt;element name="relatedLexiconInfo" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}relatedLexiconInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "languageDescriptionOperationInfo", propOrder = {
    "runningEnvironmentInfo",
    "relatedLexiconInfo"
})
public class LanguageDescriptionOperationInfo {

    protected RunningEnvironmentInfo runningEnvironmentInfo;
    protected RelatedLexiconInfo relatedLexiconInfo;

    /**
     * Gets the value of the runningEnvironmentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RunningEnvironmentInfo }
     *     
     */
    public RunningEnvironmentInfo getRunningEnvironmentInfo() {
        return runningEnvironmentInfo;
    }

    /**
     * Sets the value of the runningEnvironmentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RunningEnvironmentInfo }
     *     
     */
    public void setRunningEnvironmentInfo(RunningEnvironmentInfo value) {
        this.runningEnvironmentInfo = value;
    }

    /**
     * Gets the value of the relatedLexiconInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RelatedLexiconInfo }
     *     
     */
    public RelatedLexiconInfo getRelatedLexiconInfo() {
        return relatedLexiconInfo;
    }

    /**
     * Sets the value of the relatedLexiconInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatedLexiconInfo }
     *     
     */
    public void setRelatedLexiconInfo(RelatedLexiconInfo value) {
        this.relatedLexiconInfo = value;
    }

}
