//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.29 at 02:58:21 PM EEST 
//


package eu.openminted.registry.domain;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for languageDescriptionInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="languageDescriptionInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resourceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}identificationInfo"/>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}contactInfo"/>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}versionInfo" minOccurs="0"/>
 *         &lt;element name="validationInfos" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}validationInfo" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}usageInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}resourceDocumentationInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}resourceCreationInfo" minOccurs="0"/>
 *         &lt;element name="distributionInfos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}datasetDistributionInfo" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="languageDescriptionType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="grammar"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}languageDescriptionEncodingInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}languageDescriptionOperationInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}languageDescriptionPerformanceInfo" minOccurs="0"/>
 *         &lt;element name="languageDescriptionMediaType">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}languageDescriptionTextInfo"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "languageDescriptionInfo", propOrder = {
    "resourceType",
    "identificationInfo",
    "contactInfo",
    "versionInfo",
    "validationInfos",
    "usageInfo",
    "resourceDocumentationInfo",
    "resourceCreationInfo",
    "distributionInfos",
    "languageDescriptionType",
    "languageDescriptionEncodingInfo",
    "languageDescriptionOperationInfo",
    "languageDescriptionPerformanceInfo",
    "languageDescriptionMediaType"
})
public class LanguageDescriptionInfo {

    @XmlElement(required = true)
    protected String resourceType;
    
    @XmlElement(required = true)
    protected IdentificationInfo identificationInfo;
    @XmlElement(required = true)
    protected ContactInfo contactInfo;
    protected VersionInfo versionInfo;
    
    @XmlElementWrapper(name = "validationInfos")
    @XmlElement(name = "validationInfo")
    protected List<ValidationInfo> validationInfos;
    protected UsageInfo usageInfo;
    protected ResourceDocumentationInfo resourceDocumentationInfo;
    protected ResourceCreationInfo resourceCreationInfo;
    
    @XmlElementWrapper(name = "distributionInfos")
    @XmlElement(name = "datasetDistributionInfo", required = true)
    protected List<DatasetDistributionInfo> distributionInfos;
    
    @XmlElement(required = true)
    protected String languageDescriptionType;
    protected LanguageDescriptionEncodingInfo languageDescriptionEncodingInfo;
    protected LanguageDescriptionOperationInfo languageDescriptionOperationInfo;
    protected LanguageDescriptionPerformanceInfo languageDescriptionPerformanceInfo;
    @XmlElement(required = true)
    protected LanguageDescriptionMedia languageDescriptionMediaType;

    /**
     * Gets the value of the resourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * Sets the value of the resourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceType(String value) {
        this.resourceType = value;
    }

    /**
     * Gets the value of the identificationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificationInfo }
     *     
     */
    public IdentificationInfo getIdentificationInfo() {
        return identificationInfo;
    }

    /**
     * Sets the value of the identificationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificationInfo }
     *     
     */
    public void setIdentificationInfo(IdentificationInfo value) {
        this.identificationInfo = value;
    }

    /**
     * Gets the value of the contactInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ContactInfo }
     *     
     */
    public ContactInfo getContactInfo() {
        return contactInfo;
    }

    /**
     * Sets the value of the contactInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactInfo }
     *     
     */
    public void setContactInfo(ContactInfo value) {
        this.contactInfo = value;
    }

    /**
     * Gets the value of the versionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link VersionInfo }
     *     
     */
    public VersionInfo getVersionInfo() {
        return versionInfo;
    }

    /**
     * Sets the value of the versionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersionInfo }
     *     
     */
    public void setVersionInfo(VersionInfo value) {
        this.versionInfo = value;
    }

    /**
     * Gets the value of the validationInfos property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationInfos }
     *     
     */
    public List<ValidationInfo> getValidationInfos() {
        return validationInfos;
    }

    /**
     * Sets the value of the validationInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationInfos }
     *     
     */
    public void setValidationInfos(List<ValidationInfo> value) {
        this.validationInfos = value;
    }

    /**
     * Gets the value of the usageInfo property.
     * 
     * @return
     *     possible object is
     *     {@link UsageInfo }
     *     
     */
    public UsageInfo getUsageInfo() {
        return usageInfo;
    }

    /**
     * Sets the value of the usageInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsageInfo }
     *     
     */
    public void setUsageInfo(UsageInfo value) {
        this.usageInfo = value;
    }

    /**
     * Gets the value of the resourceDocumentationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceDocumentationInfo }
     *     
     */
    public ResourceDocumentationInfo getResourceDocumentationInfo() {
        return resourceDocumentationInfo;
    }

    /**
     * Sets the value of the resourceDocumentationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceDocumentationInfo }
     *     
     */
    public void setResourceDocumentationInfo(ResourceDocumentationInfo value) {
        this.resourceDocumentationInfo = value;
    }

    /**
     * Gets the value of the resourceCreationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceCreationInfo }
     *     
     */
    public ResourceCreationInfo getResourceCreationInfo() {
        return resourceCreationInfo;
    }

    /**
     * Sets the value of the resourceCreationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceCreationInfo }
     *     
     */
    public void setResourceCreationInfo(ResourceCreationInfo value) {
        this.resourceCreationInfo = value;
    }

    /**
     * Gets the value of the distributionInfos property.
     * 
     * @return
     *     possible object is
     *     {@link DistributionInfos }
     *     
     */
    public List<DatasetDistributionInfo> getDistributionInfos() {
        return distributionInfos;
    }

    /**
     * Sets the value of the distributionInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionInfos }
     *     
     */
    public void setDistributionInfos(List<DatasetDistributionInfo> value) {
        this.distributionInfos = value;
    }

    /**
     * Gets the value of the languageDescriptionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageDescriptionType() {
        return languageDescriptionType;
    }

    /**
     * Sets the value of the languageDescriptionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageDescriptionType(String value) {
        this.languageDescriptionType = value;
    }

    /**
     * Gets the value of the languageDescriptionEncodingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageDescriptionEncodingInfo }
     *     
     */
    public LanguageDescriptionEncodingInfo getLanguageDescriptionEncodingInfo() {
        return languageDescriptionEncodingInfo;
    }

    /**
     * Sets the value of the languageDescriptionEncodingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageDescriptionEncodingInfo }
     *     
     */
    public void setLanguageDescriptionEncodingInfo(LanguageDescriptionEncodingInfo value) {
        this.languageDescriptionEncodingInfo = value;
    }

    /**
     * Gets the value of the languageDescriptionOperationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageDescriptionOperationInfo }
     *     
     */
    public LanguageDescriptionOperationInfo getLanguageDescriptionOperationInfo() {
        return languageDescriptionOperationInfo;
    }

    /**
     * Sets the value of the languageDescriptionOperationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageDescriptionOperationInfo }
     *     
     */
    public void setLanguageDescriptionOperationInfo(LanguageDescriptionOperationInfo value) {
        this.languageDescriptionOperationInfo = value;
    }

    /**
     * Gets the value of the languageDescriptionPerformanceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageDescriptionPerformanceInfo }
     *     
     */
    public LanguageDescriptionPerformanceInfo getLanguageDescriptionPerformanceInfo() {
        return languageDescriptionPerformanceInfo;
    }

    /**
     * Sets the value of the languageDescriptionPerformanceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageDescriptionPerformanceInfo }
     *     
     */
    public void setLanguageDescriptionPerformanceInfo(LanguageDescriptionPerformanceInfo value) {
        this.languageDescriptionPerformanceInfo = value;
    }

    /**
     * Gets the value of the languageDescriptionMediaType property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageDescriptionMedia }
     *     
     */
    public LanguageDescriptionMedia getLanguageDescriptionMediaType() {
        return languageDescriptionMediaType;
    }

    /**
     * Sets the value of the languageDescriptionMediaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageDescriptionMedia }
     *     
     */
    public void setLanguageDescriptionMediaType(LanguageDescriptionMedia value) {
        this.languageDescriptionMediaType = value;
    }

}
