//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.29 at 02:58:21 PM EEST 
//


package eu.openminted.registry.domain;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for languageDescriptionEncodingInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="languageDescriptionEncodingInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="encodingLevels">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}encodingLevel" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="standardsBestPractices" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="conformanceToStandardsBestPractices" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}conformanceToStandardsBestPractices" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="theoreticModels" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}theoreticModel" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="formalisms" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="formalism" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="tasks" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="task" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="30"/>
 *                         &lt;enumeration value="anaphoraResolution"/>
 *                         &lt;enumeration value="chunking"/>
 *                         &lt;enumeration value="parsing"/>
 *                         &lt;enumeration value="npRecognition"/>
 *                         &lt;enumeration value="titlesParsing"/>
 *                         &lt;enumeration value="definitionsParsing"/>
 *                         &lt;enumeration value="analysis"/>
 *                         &lt;enumeration value="generation"/>
 *                         &lt;enumeration value="other"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="grammaticalPhenomenaCoverages" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="grammaticalPhenomenaCoverage" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="30"/>
 *                         &lt;enumeration value="clauseStructure"/>
 *                         &lt;enumeration value="ppAttachment"/>
 *                         &lt;enumeration value="npStructure"/>
 *                         &lt;enumeration value="coordination"/>
 *                         &lt;enumeration value="anaphora"/>
 *                         &lt;enumeration value="other"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="weightedGrammar" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "languageDescriptionEncodingInfoType", propOrder = {
    "encodingLevels",
    "standardsBestPractices",
    "theoreticModels",
    "formalisms",
    "tasks",
    "grammaticalPhenomenaCoverages"
})
public class LanguageDescriptionEncodingInfo {

	@XmlElementWrapper(name = "encodingLevels")
    @XmlElement(name = "encodingLevel",required = true)
    protected List<EncodingLevel> encodingLevels;
	
	@XmlElementWrapper(name = "standardsBestPractices")
    @XmlElement(name = "conformanceToStandardsBestPractices")
    protected List<ConformanceToStandardsBestPractices> standardsBestPractices;
	
	@XmlElementWrapper(name = "theoreticModels")
    @XmlElement(name = "theoreticModel")
    protected List<String> theoreticModels;
	
	@XmlElementWrapper(name = "formalisms")
    @XmlElement(name = "formalism")
    protected List<String> formalisms;
    
    @XmlElementWrapper(name = "tasks")
    @XmlElement(name = "task")
    protected List<String> tasks;

    protected GrammaticalPhenomenaCoverages grammaticalPhenomenaCoverages;

    /**
     * Gets the value of the encodingLevels property.
     * 
     * @return
     *     possible object is
     *     {@link EncodingLevels }
     *     
     */
    public List<EncodingLevel> getEncodingLevels() {
        return encodingLevels;
    }

    /**
     * Sets the value of the encodingLevels property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncodingLevels }
     *     
     */
    public void setEncodingLevels(List<EncodingLevel> value) {
        this.encodingLevels = value;
    }

    /**
     * Gets the value of the standardsBestPractices property.
     * 
     * @return
     *     possible object is
     *     {@link StandardsBestPractices }
     *     
     */
    public List<ConformanceToStandardsBestPractices> getStandardsBestPractices() {
        return standardsBestPractices;
    }

    /**
     * Sets the value of the standardsBestPractices property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardsBestPractices }
     *     
     */
    public void setStandardsBestPractices(List<ConformanceToStandardsBestPractices> value) {
        this.standardsBestPractices = value;
    }

    /**
     * Gets the value of the theoreticModels property.
     * 
     * @return
     *     possible object is
     *     {@link TheoreticModels }
     *     
     */
    public List<String> getTheoreticModels() {
        return theoreticModels;
    }

    /**
     * Sets the value of the theoreticModels property.
     * 
     * @param value
     *     allowed object is
     *     {@link TheoreticModels }
     *     
     */
    public void setTheoreticModels(List<String> value) {
        this.theoreticModels = value;
    }

    /**
     * Gets the value of the formalisms property.
     * 
     * @return
     *     possible object is
     *     {@link Formalisms }
     *     
     */
    public List<String> getFormalisms() {
        return formalisms;
    }

    /**
     * Sets the value of the formalisms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Formalisms }
     *     
     */
    public void setFormalisms(List<String> value) {
        this.formalisms = value;
    }

    /**
     * Gets the value of the tasks property.
     * 
     * @return
     *     possible object is
     *     {@link Tasks }
     *     
     */
    public List<String> getTasks() {
        return tasks;
    }

    /**
     * Sets the value of the tasks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tasks }
     *     
     */
    public void setTasks(List<String> value) {
        this.tasks = value;
    }

    /**
     * Gets the value of the grammaticalPhenomenaCoverages property.
     * 
     * @return
     *     possible object is
     *     {@link GrammaticalPhenomenaCoverages }
     *     
     */
    public GrammaticalPhenomenaCoverages getGrammaticalPhenomenaCoverages() {
        return grammaticalPhenomenaCoverages;
    }

    /**
     * Sets the value of the grammaticalPhenomenaCoverages property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrammaticalPhenomenaCoverages }
     *     
     */
    public void setGrammaticalPhenomenaCoverages(GrammaticalPhenomenaCoverages value) {
        this.grammaticalPhenomenaCoverages = value;
    }

}
