//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.03 at 03:00:05 PM EEST 
//


package eu.openminted.registry.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}modelTextInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modelTextInfo"
})
public class ModelMediaType {

    protected ModelTextInfoType modelTextInfo;

    /**
     * Gets the value of the modelTextInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ModelTextInfoType }
     *     
     */
    public ModelTextInfoType getModelTextInfo() {
        return modelTextInfo;
    }

    /**
     * Sets the value of the modelTextInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelTextInfoType }
     *     
     */
    public void setModelTextInfo(ModelTextInfoType value) {
        this.modelTextInfo = value;
    }

}
