//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.29 at 02:58:21 PM EEST 
//


package eu.openminted.registry.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for relatedLexiconInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relatedLexiconInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="relatedLexiconType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="included"/>
 *               &lt;enumeration value="attached"/>
 *               &lt;enumeration value="compatible"/>
 *               &lt;enumeration value="none"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="attachedLexiconPosition" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="500"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="compatibleLexiconType" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="wordnet"/>
 *               &lt;enumeration value="wordlist"/>
 *               &lt;enumeration value="morphologicalLexicon"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relatedLexiconInfoType", propOrder = {
    "relatedLexiconType",
    "attachedLexiconPosition",
    "compatibleLexiconType"
})
public class RelatedLexiconInfo {

    @XmlElement(required = true)
    protected String relatedLexiconType;
    protected String attachedLexiconPosition;
    protected List<String> compatibleLexiconType;

    /**
     * Gets the value of the relatedLexiconType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedLexiconType() {
        return relatedLexiconType;
    }

    /**
     * Sets the value of the relatedLexiconType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedLexiconType(String value) {
        this.relatedLexiconType = value;
    }

    /**
     * Gets the value of the attachedLexiconPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachedLexiconPosition() {
        return attachedLexiconPosition;
    }

    /**
     * Sets the value of the attachedLexiconPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachedLexiconPosition(String value) {
        this.attachedLexiconPosition = value;
    }

    /**
     * Gets the value of the compatibleLexiconType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compatibleLexiconType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompatibleLexiconType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCompatibleLexiconType() {
        if (compatibleLexiconType == null) {
            compatibleLexiconType = new ArrayList<String>();
        }
        return this.compatibleLexiconType;
    }

}
